export interface Game {
  id: string;
  title: string;
  category: string;
  suitability: string;
  shortDesc: string;
  longDesc: string;
  difficulty: number;
  tags: string[];
  playStyle: string;
  actionType: string;
  image: string;
  developer?: string;
  publisher?: string;
  comfortRating?: string;
  controllers?: string;
  spaceRequired?: string;
  playerMode?: string;
  features?: string[];
}

export const gamesData: Game[] = [
  // 1. Horror Experiences
  {
    id: "richies-plank",
    title: "Richie's Plank Experience",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Walk a thin plank 80 stories high and face your fear of heights.",
    longDesc: "Richie's Plank Experience is a psychological thrill ride. Placed 80 stories above the ground, walk a narrow wooden plank and decide if you have the nerve to step off. It is designed to evoke strong physiological reactions, making it the perfect showcase for the power of immersive virtual reality. Includes multiple secondary modes such as superhero flying academy, firefighting simulators, and writing tools.",
    difficulty: 4,
    tags: ["Thrill", "Heights", "Short Play", "Immersive"],
    playStyle: "Standing/Room-Scale",
    actionType: "Simulation",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/517160/header.jpg",
    developer: "Toast Interactive",
    publisher: "Toast Interactive",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "1.8 GB",
    playerMode: "Single User",
    features: [
      "Real-world plank setup integration",
      "Stomach-dropping height simulation",
      "Superhero flight mode",
      "Firefighting mini-missions",
      "Skybrush skywriting tool"
    ]
  },
  {
    id: "sleep-watch",
    title: "Sleep Watch",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Stay alert and survive the horrors lurking in the dark.",
    longDesc: "Sleep Watch places you in a dark and eerie environment where survival depends on your alertness and quick thinking. You must monitor multiple security cameras, check the hallway shadows, and keep your composure as tension rises in this sleep paralysis horror simulation.",
    difficulty: 4,
    tags: ["Survival", "Suspense", "Jump Scares", "Dark"],
    playStyle: "Sitting/Standing",
    actionType: "Survival Horror",
    image: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    developer: "Cyberia Studios",
    publisher: "Cyberia Studios",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "1.2 GB",
    playerMode: "Single User",
    features: [
      "Real-time security monitor feed",
      "Heart-rate monitoring mechanics",
      "Randomized horror triggers",
      "Light and sound navigation puzzles"
    ]
  },
  {
    id: "face-your-fears",
    title: "Face Your Fears",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Confront your deepest fears in spine-chilling scenarios.",
    longDesc: "Face Your Fears exposes you to common phobias and horror scenarios in full 360-degree immersion. From haunted houses to towering heights and paranormal entities, this experience is designed to test your limits and get your adrenaline pumping.",
    difficulty: 5,
    tags: ["Atmospheric", "Spooky", "Short Play", "Jump Scares"],
    playStyle: "Sitting",
    actionType: "Interactive Experience",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    developer: "Turtle Rock Studios",
    publisher: "Warner Bros. Interactive",
    comfortRating: "Intense",
    controllers: "Gaze/Touch Controllers",
    spaceRequired: "3.5 GB",
    playerMode: "Single User",
    features: [
      "Multi-sensory phobia modules",
      "Haunted children's bedroom module",
      "Giant skyscraper attack module",
      "Deep-sea ghost ship experience"
    ]
  },
  {
    id: "cursed-night-house",
    title: "Cursed Night – The House",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Explore a haunted house and escape its cursed entities.",
    longDesc: "Cursed Night: The House is a narrative-driven horror game where you explore a derelict, cursed mansion. Solve basic puzzles, find clues, and evade the malevolent spirits that haunt the corridors before it is too late.",
    difficulty: 4,
    tags: ["Exploration", "Puzzle", "Escape Room", "Spooky"],
    playStyle: "Standing/Room-Scale",
    actionType: "Exploration Horror",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1740570/header.jpg",
    developer: "Red Soul Games",
    publisher: "Red Soul Games",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "4.0 GB",
    playerMode: "Single User",
    features: [
      "Physics-based puzzle objects",
      "Ambient lighting toggle mechanics",
      "3D spatial audio whispers",
      "Lock-and-key room locks"
    ]
  },
  {
    id: "z-show",
    title: "Z-Show",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Survive a deadly zombie-infested television game show.",
    longDesc: "Z-Show casts you as a contestant in an apocalyptic, dystopian game show where the prize is your life. Face waves of zombies, activate environmental traps, and entertain the audience to secure supply drops in this high-tension horror shootout.",
    difficulty: 4,
    tags: ["Zombies", "Survival", "Action", "Arena"],
    playStyle: "Standing",
    actionType: "Zombie Combat",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    developer: "Pixelity Games",
    publisher: "Pixelity Games",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "2.1 GB",
    playerMode: "Single User",
    features: [
      "Dystopian arena game show layout",
      "Crowd noise feedback audio loop",
      "Interactive stage environmental traps",
      "High-score wave multiplier tracker"
    ]
  },
  {
    id: "cursed-echoes",
    title: "Cursed Echoes",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Investigate whispering ruins and piece together cursed histories.",
    longDesc: "Cursed Echoes is a psychological thriller that relies on spatial audio. Navigate shifting dark corridors, solve auditory puzzles, and avoid spectral entities that react to every sound you make in the real world.",
    difficulty: 4,
    tags: ["Audio-focus", "Mystery", "Atmospheric", "Spooky"],
    playStyle: "Standing/Room-Scale",
    actionType: "Psychological Horror",
    image: "https://images.unsplash.com/photo-1505635338219-0a113f66a337?auto=format&fit=crop&w=600&q=80",
    developer: "Soundscape VR",
    publisher: "Soundscape VR",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.8 GB",
    playerMode: "Single User",
    features: [
      "Acoustic-guided gameplay",
      "Spatial echo-location scanners",
      "Shifting non-euclidean labyrinth",
      "Microphone audio feedback detection"
    ]
  },
  {
    id: "descending",
    title: "Descending",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Descend into dark caverns with only a flashlight and your wits.",
    longDesc: "Descending puts you in the shoes of a deep cave explorer. As your ropes break, you find yourself trapped in an ancient, uncharted cavern system. Explore narrow tunnels, manage your oxygen, and discover what lurks in the absolute dark.",
    difficulty: 5,
    tags: ["Caves", "Exploration", "Survival", "Claustrophobic"],
    playStyle: "Standing/Room-Scale",
    actionType: "Survival Horror",
    image: "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=600&q=80",
    developer: "Vertigo Games",
    publisher: "Vertigo Games",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "5.2 GB",
    playerMode: "Single User",
    features: [
      "Rappelling and rock climbing physics",
      "Realistic flashlight battery mechanics",
      "Cave-in survival navigation scenarios",
      "Mysterious runic text decryption"
    ]
  },
  {
    id: "panic-room-mr",
    title: "Panic Room MR",
    category: "Horror Experiences",
    suitability: "Teens & Adults",
    shortDesc: "Transform your actual room into a haunted mixed reality escape game.",
    longDesc: "Panic Room MR uses advanced pass-through mixed reality. Watch as ghosts break through your physical walls and haunted objects float in your living room. Solve clues anchored in your physical space to escape the curse.",
    difficulty: 4,
    tags: ["Mixed Reality", "Escape Room", "Interactive", "Spooky"],
    playStyle: "Room-Scale",
    actionType: "Mixed Reality Escape",
    image: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    developer: "Resolution Games",
    publisher: "Resolution Games",
    comfortRating: "Comfortable",
    controllers: "Hand Tracking / Touch",
    spaceRequired: "900 MB",
    playerMode: "Single User / Co-op",
    features: [
      "Pass-through room mesh boundaries",
      "Anchored holographic props",
      "Furniture collider recognition",
      "Local multiplayer escape cooperation"
    ]
  },

  // 2. Fighting & Action Games
  {
    id: "ninja-legends",
    title: "Ninja Legends",
    category: "Fighting & Action Games",
    suitability: "Ages 10+",
    shortDesc: "Wield dual katanas and slice through waves of ninja enemies.",
    longDesc: "Ninja Legends is an action-heavy combat game where you face waves of skilled enemies using a wide variety of ninja weaponry. Deflect arrows, block attacks, and unleash powerful shadow attacks in high-paced physical melee combat.",
    difficulty: 3,
    tags: ["Melee", "Swordplay", "Active", "Combat"],
    playStyle: "Standing/Room-Scale",
    actionType: "Action Combat",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1080750/header.jpg",
    developer: "Coinflip Studios",
    publisher: "Coinflip Studios",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "3.2 GB",
    playerMode: "Single User",
    features: [
      "18 weapons (Katanas, claws, bow)",
      "Real-time deflection and parrying",
      "Sword slice physics system",
      "Slow-motion cinematic execution states"
    ]
  },
  {
    id: "creed-rise-glory",
    title: "Creed",
    category: "Fighting & Action Games",
    suitability: "Ages 10+",
    shortDesc: "Step into the boxing ring and fight your way to the top.",
    longDesc: "Creed (Rise to Glory) lets you train under Rocky Balboa and fight against legendary boxers. Features responsive boxing physics, stamina-draining physical movement, and multiplayer matches that test your endurance and boxing skills.",
    difficulty: 4,
    tags: ["Sports", "Boxing", "Active", "Simulation"],
    playStyle: "Standing",
    actionType: "Active Boxing",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/945980/header.jpg",
    developer: "Survios",
    publisher: "Survios",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "4.5 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Phantom Melee fatigue mechanic",
      "Rocky Balboa training gyms",
      "Championship campaign mode",
      "Cross-platform PvP boxing matches"
    ]
  },
  {
    id: "100-day-siege",
    title: "100 Day Siege",
    category: "Fighting & Action Games",
    suitability: "Ages 10+",
    shortDesc: "Defend your castle gates against waves of fantasy armies.",
    longDesc: "100 Day Siege is a tactical defensive combat game. Position archers, pour boiling oil, and step onto the ramparts with your broadsword to defend your kingdom's final outpost against giants, orcs, and siege engines.",
    difficulty: 3,
    tags: ["Defensive", "Combat", "Tactical", "Medieval"],
    playStyle: "Standing",
    actionType: "Castle Defense",
    image: "https://images.unsplash.com/photo-1533228894184-754f91165a2d?auto=format&fit=crop&w=600&q=80",
    developer: "Skydance Interactive",
    publisher: "Skydance Interactive",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "2.8 GB",
    playerMode: "Single User",
    features: [
      "Rampart archer post setup",
      "Physical archery mechanics",
      "Boiling oil kettle physics triggers",
      "Multi-stage fantasy wave sieges"
    ]
  },
  {
    id: "legacy-awake",
    title: "Legacy Awake",
    category: "Fighting & Action Games",
    suitability: "Ages 10+",
    shortDesc: "Embark on an epic fantasy quest to awaken ancient guardians.",
    longDesc: "Legacy Awake places you in a stunning high-fantasy realm. Solve puzzle gates, learn spells, and fight colossal guardians using magical shields and swords to bring light back to a forgotten kingdom.",
    difficulty: 3,
    tags: ["Fantasy", "Spells", "Adventure", "Combat"],
    playStyle: "Standing/Room-Scale",
    actionType: "Fantasy Action",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    developer: "Polyarc Games",
    publisher: "Polyarc Games",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "3.6 GB",
    playerMode: "Single User",
    features: [
      "Hand gesture casting mechanics",
      "Ancient puzzle portal structures",
      "Titan climbing combat battles",
      "High-fidelity high-fantasy art direction"
    ]
  },

  // 3. Driving & Racing Simulation
  {
    id: "just-drive",
    title: "Just Drive",
    category: "Driving & Racing Simulation",
    suitability: "All Ages",
    shortDesc: "Take the wheel and enjoy a relaxing or thrilling drive.",
    longDesc: "Just Drive is an open-road driving experience focused on realism and chill driving vibes. Choose from sports cars to trucks, explore scenic highways, and master vehicle handling in realistic weather and traffic conditions.",
    difficulty: 2,
    tags: ["Simulation", "Driving", "Scenic", "Relaxing"],
    playStyle: "Sitting",
    actionType: "Driving Simulation",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80",
    developer: "Sector3 Studios",
    publisher: "Sector3 Studios",
    comfortRating: "Moderate",
    controllers: "Steering Wheel/Touch",
    spaceRequired: "6.0 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Fully interactive dashboard dials",
      "Live weather & daylight cycles",
      "Interactive steering and gears",
      "Intelligent road traffic AI"
    ]
  },
  {
    id: "car-parking-sim",
    title: "Car Parking Simulator",
    category: "Driving & Racing Simulation",
    suitability: "All Ages",
    shortDesc: "Master the art of parking in various realistic challenges.",
    longDesc: "Car Parking Simulator tests your driving precision. Learn parallel parking, reverse parking, and navigate tight spaces across multiple realistic vehicle types, complete with virtual mirrors, steering wheel controls, and parking sensors.",
    difficulty: 3,
    tags: ["Skill-based", "Driving", "Precision", "Relaxing"],
    playStyle: "Sitting",
    actionType: "Precision Simulation",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1324410/header.jpg",
    developer: "Aviary Games",
    publisher: "Aviary Games",
    comfortRating: "Comfortable",
    controllers: "Touch/Steering Wheel",
    spaceRequired: "1.2 GB",
    playerMode: "Single User",
    features: [
      "Functional vehicle side mirrors",
      "Audio-assist parking sensors",
      "100+ precision driving puzzles",
      "Interactive physics gear shifting"
    ]
  },
  {
    id: "speed-racer",
    title: "Speed Racer",
    category: "Driving & Racing Simulation",
    suitability: "All Ages",
    shortDesc: "Race at breakneck speeds down futuristic, looping tracks.",
    longDesc: "Speed Racer is a high-speed arcade racing simulator. Grip the steering wheel and speed down gravity-defying vertical loops, boost pads, and drift corners against competitive AI in a neon-drenched skyway.",
    difficulty: 3,
    tags: ["Speed", "Racing", "Arcade", "Thrill"],
    playStyle: "Sitting",
    actionType: "Arcade Racing",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80",
    developer: "Codemasters",
    publisher: "Codemasters",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "4.5 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Vertical gravity-defying tracks",
      "Drifting speed boost multiplier",
      "Sky-high vertical loops",
      "Immersive dashboard cockpit HUD"
    ]
  },
  {
    id: "z-race",
    title: "Z Race",
    category: "Driving & Racing Simulation",
    suitability: "All Ages",
    shortDesc: "Pilot futuristic hovercrafts in zero-gravity racing leagues.",
    longDesc: "Z Race is a fresh hovercraft racing game. Fly through rings, collect boosts, and maneuver through zero-gravity tunnels. Features high visual fidelity and responsive flight controls tailored for VR cockpits.",
    difficulty: 4,
    tags: ["Sci-Fi", "Zero-G", "Racing", "Futuristic"],
    playStyle: "Sitting",
    actionType: "Hovercraft Racing",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1348750/header.jpg",
    developer: "XOCUS",
    publisher: "XOCUS",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "3.0 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Zero-gravity flight mechanics",
      "Vibrant cybernetic space tracks",
      "Speed gate acceleration rings",
      "Global leaderboard time trials"
    ]
  },
  {
    id: "formula-x",
    title: "Formula X",
    category: "Driving & Racing Simulation",
    suitability: "Teens & Adults",
    shortDesc: "Experience the speed and G-forces of professional F1 track racing.",
    longDesc: "Formula X brings F1 simulation to VR. Complete with tire management, pit stops, and realistic steering feedback, race on world-famous circuits and shave milliseconds off your lap time in search of the podium.",
    difficulty: 4,
    tags: ["Formula", "Simulation", "Tracks", "Precision"],
    playStyle: "Sitting",
    actionType: "F1 Racing Sim",
    image: "https://images.unsplash.com/photo-1560855814-114afabdfa20?auto=format&fit=crop&w=600&q=80",
    developer: "Kunos Simulazioni",
    publisher: "Kunos Simulazioni",
    comfortRating: "Moderate",
    controllers: "Steering Wheel/Touch",
    spaceRequired: "8.0 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Live telemetry dash stats",
      "Dynamic tire degradation & pits",
      "Force-feedback steering integration",
      "Laser-scanned real world track maps"
    ]
  },
  {
    id: "bus-parking-vr",
    title: "Bus Parking VR",
    category: "Driving & Racing Simulation",
    suitability: "All Ages",
    shortDesc: "Steer and park double-decker buses in heavy city traffic.",
    longDesc: "Bus Parking VR elevates the parking simulator genre. Manage the massive turn radius of city buses, watch your mirrors, avoid pedestrians, and slide into narrow terminal bays in structured parking scenarios.",
    difficulty: 4,
    tags: ["Bus", "Parking", "Heavy Vehicle", "Precision"],
    playStyle: "Sitting",
    actionType: "Parking Simulator",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    developer: "SimuGames",
    publisher: "SimuGames",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.8 GB",
    playerMode: "Single User",
    features: [
      "Detailed bus cockpit instruments",
      "Platform passenger alignment markers",
      "Integrated rearview mirror cameras",
      "Multiple articulated vehicle chassis"
    ]
  },

  // 4. Adventure & Thrill Rides
  {
    id: "rollercoasters-coastal",
    title: "Roller Coasters / Coastal Combat",
    category: "Adventure & Thrill Rides",
    suitability: "All Ages",
    shortDesc: "Experience roller coaster loops and futuristic air-battles.",
    longDesc: "Roller Coasters / Coastal Combat blends two extreme experiences. First, enjoy breathtaking, stomach-dropping loops on virtual coasters. Then, fly a combat jet over beautiful coastal landscapes, dogfighting enemy fighters in full 3D space.",
    difficulty: 4,
    tags: ["Thrill", "Rollercoaster", "Flight", "Speed"],
    playStyle: "Sitting",
    actionType: "Thrill Ride",
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80",
    developer: "Coaster Games",
    publisher: "Coaster Games",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "3.0 GB",
    playerMode: "Single User",
    features: [
      "Desert canyon and city-scape coaster runs",
      "Interactive military flight cockpit",
      "Weapon tracking laser targeters",
      "Physiological stomach-drop curves"
    ]
  },
  {
    id: "ocean-rift",
    title: "Ocean Rift",
    category: "Adventure & Thrill Rides",
    suitability: "All Ages",
    shortDesc: "Explore a beautiful aquatic world and swim with sharks.",
    longDesc: "Ocean Rift is the world's first VR aquatic safari park. Explore a vibrant underwater world containing sharks, dolphins, whales, and pre-historic sea creatures. Visit different environments from shallow coral reefs to the deep, dark ocean abyss.",
    difficulty: 1,
    tags: ["Nature", "Relaxing", "Exploration", "Education"],
    playStyle: "Sitting/Standing",
    actionType: "Aquatic Safari",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/422760/header.jpg",
    developer: "Llyr Ap Cenydd",
    publisher: "Llyr Ap Cenydd",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "2.4 GB",
    playerMode: "Single User",
    features: [
      "14 detailed underwater biomes",
      "AI-driven predator/prey behavior",
      "Educational narrative guides",
      "Interactive whale and turtle feed prompts"
    ]
  },
  {
    id: "deepwater",
    title: "Deepwater",
    category: "Adventure & Thrill Rides",
    suitability: "All Ages",
    shortDesc: "Pilot a deep-sea submersible and explore shipwrecks and thermal vents.",
    longDesc: "Deepwater puts you inside a high-tech submarine research vessel. Descend to the Mariana Trench, guide robotic claws to collect deep-sea flora, and illuminate mysterious trenches filled with glowing bioluminescent life.",
    difficulty: 2,
    tags: ["Submarine", "Deep-sea", "Nature", "Relaxing"],
    playStyle: "Sitting",
    actionType: "Aquatic Exploration",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80",
    developer: "SubSoft",
    publisher: "SubSoft",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "2.1 GB",
    playerMode: "Single User",
    features: [
      "Glass-dome cockpit navigation",
      "Hydrodynamic grabber claw controls",
      "Fauna photography collection logs",
      "High-power spotlight pathfinder system"
    ]
  },
  {
    id: "escape-room",
    title: "Escape Room",
    category: "Adventure & Thrill Rides",
    suitability: "All Ages",
    shortDesc: "Solve environmental puzzles to escape locked rooms under pressure.",
    longDesc: "Escape Room VR presents multiple themed rooms: an ancient Pharaoh's tomb, a high-tech hacker den, and a mad scientist's lab. Work together or race the clock, uncovering hidden keys and deciphering cryptographic codes.",
    difficulty: 3,
    tags: ["Puzzles", "Escape", "Co-op", "Brain"],
    playStyle: "Standing/Room-Scale",
    actionType: "Puzzle Adventure",
    image: "https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?auto=format&fit=crop&w=600&q=80",
    developer: "Fireproof Games",
    publisher: "Fireproof Games",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "2.6 GB",
    playerMode: "Single User / Co-op",
    features: [
      "Multi-stage escape theme rooms",
      "Physics dials, keys, and gears",
      "Interactive puzzle clue journals",
      "Timer-based challenge modes"
    ]
  },
  {
    id: "coaster-combat",
    title: "Coaster Combat",
    category: "Adventure & Thrill Rides",
    suitability: "All Ages",
    shortDesc: "Shoot targets and dodge obstacles while riding extreme rollercoasters.",
    longDesc: "Coaster Combat turns the classic rollercoaster into an active shooting gallery. Wield dual laser blasters, shoot glowing targets along the rails, lean physical left and right to dodge obstacles, and beat the high score.",
    difficulty: 3,
    tags: ["Rollercoaster", "Shooter", "Active", "Thrill"],
    playStyle: "Sitting",
    actionType: "Rollercoaster Shooter",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    developer: "Force Field",
    publisher: "Force Field",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "1.5 GB",
    playerMode: "Single User",
    features: [
      "Fast-paced rail shooter targeting",
      "Dual rapid-fire neon blasters",
      "Lean-to-dodge obstacle mechanics",
      "Dynamic scoreboard combos and multipliers"
    ]
  },
  {
    id: "park",
    title: "Park",
    category: "Adventure & Thrill Rides",
    suitability: "All Ages",
    shortDesc: "Walk through prehistoric valleys and interact with dinosaurs.",
    longDesc: "Park takes you on a safari through a lush prehistoric reserve. Stand face-to-face with a towering Brachiosaurus, feed a baby Triceratops, and escape a Tyrannosaurus Rex in a thrilling, cinematic safari loop.",
    difficulty: 1,
    tags: ["Dinosaurs", "Safari", "Nature", "Cinematic"],
    playStyle: "Sitting/Standing",
    actionType: "Nature Safari",
    image: "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?auto=format&fit=crop&w=600&q=80",
    developer: "Jurassic VR",
    publisher: "Jurassic VR",
    comfortRating: "Comfortable",
    controllers: "Gaze/Touch Controllers",
    spaceRequired: "4.1 GB",
    playerMode: "Single User",
    features: [
      "Life-size dinosaur encounter zones",
      "Detailed foliage and terrain physics",
      "Prehistoric reserve truck trail ride",
      "Wildlife snapshot photo log rewards"
    ]
  },

  // 5. Shooting Games
  {
    id: "space-pirate",
    title: "Space Pirate Trainer",
    category: "Shooting Games",
    suitability: "Ages 12+",
    shortDesc: "Defend yourself against swarms of incoming space drones.",
    longDesc: "Space Pirate Trainer is the official trainer for wannabe space pirates. Fire your blasters, deflect lasers with a energy shield, and dodge incoming fire in slow motion in this arcade-style score-chasing shootout.",
    difficulty: 3,
    tags: ["Sci-Fi", "Shooter", "Active", "Arcade"],
    playStyle: "Standing/Room-Scale",
    actionType: "Wave Shooter",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/418650/header.jpg",
    developer: "I-Illusions",
    publisher: "I-Illusions",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.6 GB",
    playerMode: "Single User / Arena",
    features: [
      "6 weapon types (lasers, rails, ropes)",
      "Physical mirror reflection shields",
      "Bullet-time slowdown drone dodges",
      "Global leaderboards score tracking"
    ]
  },
  {
    id: "repossessed-zombie",
    title: "Repossessed",
    category: "Shooting Games",
    suitability: "Ages 12+",
    shortDesc: "Fight for survival against hordes of terrifying zombies.",
    longDesc: "Repossessed is an intense arcade zombie shooter. Armed with pistols, shotguns, and rifles, defend your position as hordes of infected rush at you. Quick reloading, steady aim, and spatial awareness are critical to survival.",
    difficulty: 4,
    tags: ["Zombies", "Shooter", "Scary", "Action"],
    playStyle: "Standing",
    actionType: "Zombie Survival",
    image: "https://images.unsplash.com/photo-1601513525393-832777b9bb7a?auto=format&fit=crop&w=600&q=80",
    developer: "Indie Devs",
    publisher: "Indie Devs",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "2.0 GB",
    playerMode: "Single User",
    features: [
      "Tactical reloading physics models",
      "Shotgun slide pumps",
      "Fortified window wave blockers",
      "Flashlight directional darkness overlay"
    ]
  },
  {
    id: "anshar-2",
    title: "Anshar 2",
    category: "Shooting Games",
    suitability: "Ages 10+",
    shortDesc: "Pilot a space fighter jet in fast-paced sci-fi dogfights.",
    longDesc: "Anshar 2: Hyperdrive puts you inside the cockpit of a fighter starship. Loop, barrel-roll, and lock missiles onto enemy fleets across deep space, asteroid fields, and planetary surfaces in full 3D dogfights.",
    difficulty: 4,
    tags: ["Space", "Flight", "Jet", "Sci-Fi"],
    playStyle: "Sitting/Standing",
    actionType: "Space Dogfight",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1579730/header.jpg",
    developer: "OZWE Games",
    publisher: "OZWE Games",
    comfortRating: "Moderate",
    controllers: "Touch Controllers / Gamepad",
    spaceRequired: "2.2 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Dynamic 3rd-person & cockpit cams",
      "Multi-lock missile targeting arrays",
      "Full 360 space debris battle rings",
      "10-stage cinematic mission campaign"
    ]
  },
  {
    id: "spatial-web-shooter",
    title: "Spatial Web Shooter",
    category: "Shooting Games",
    suitability: "Ages 8+",
    shortDesc: "Shoot cyber-webs to trap and capture waves of robot spider drones.",
    longDesc: "Spatial Web Shooter is a high-tech arcade shootout. Launch electrical, sticky cybernetic webs from your wrists to tie up and disable mechanical spiders climbing up your physical space walls.",
    difficulty: 2,
    tags: ["Active", "Robots", "Sci-Fi", "Score-chase"],
    playStyle: "Standing/Room-Scale",
    actionType: "Target Shooter",
    image: "https://images.unsplash.com/photo-1527853787696-f7be74f2e39a?auto=format&fit=crop&w=600&q=80",
    developer: "WebTech",
    publisher: "WebTech",
    comfortRating: "Comfortable",
    controllers: "Hand Tracking / Touch",
    spaceRequired: "950 MB",
    playerMode: "Single User",
    features: [
      "Flick-wrist sticky web casting",
      "Physics-tension line pull",
      "Fracturing mechanical spider parts",
      "Automated laser sight assists"
    ]
  },
  {
    id: "bodycam-unrecord",
    title: "Bodycam Unrecord",
    category: "Shooting Games",
    suitability: "Teens & Adults",
    shortDesc: "Experience ultra-realistic tactical military combat via a bodycam lens.",
    longDesc: "Bodycam Unrecord is a tactical shooter focused on realism. Moving through deserted industrial complexes, reload realistic weapons, lean around corners, and communicate with your squad using real bodycam angles.",
    difficulty: 5,
    tags: ["Realism", "Tactical", "Military", "Co-op"],
    playStyle: "Standing/Room-Scale",
    actionType: "Tactical Shooter",
    image: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?auto=format&fit=crop&w=600&q=80",
    developer: "Tactical Games",
    publisher: "Tactical Games",
    comfortRating: "Intense",
    controllers: "Touch Controllers",
    spaceRequired: "6.2 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Bodycam style visual filters",
      "Manual tactical weapon reloads",
      "S.W.A.T squad briefing modes",
      "Directional spatial audio alerts"
    ]
  },
  {
    id: "pistol-whip",
    title: "Pistol Whip",
    category: "Shooting Games",
    suitability: "Ages 12+",
    shortDesc: "Shoot and dodge obstacles to the beat in an action rhythm game.",
    longDesc: "Pistol Whip is an action-movie rhythm shooter. Shoot, dodge, and melee through a colorful cinematic dreamscape, synchronizing your physical movements to the thumping electronic soundtrack to maximize score multiplier.",
    difficulty: 4,
    tags: ["Rhythm", "Music", "Active", "Shooter"],
    playStyle: "Standing",
    actionType: "Rhythm Shooter",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1079800/header.jpg",
    developer: "Cloudhead Games",
    publisher: "Cloudhead Games",
    comfortRating: "Moderate",
    controllers: "Touch Controllers",
    spaceRequired: "3.0 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Tempo-synchronized shooting points",
      "Action-movie style narrative campaigns",
      "Weapon configurations and skin sets",
      "Active fitness cardio tracking"
    ]
  },

  // 6. Sports & Fitness
  {
    id: "beat-saber",
    title: "Beat Saber",
    category: "Sports & Fitness",
    suitability: "All Ages",
    shortDesc: "Slash glowing neon cubes to the rhythm of high-energy music.",
    longDesc: "Beat Saber is a global rhythm sensation. Slice neon-colored cubes representing musical beats using dual laser sabers. Avoid walls, duck under obstacles, and move your body to hit the perfect combo in an immersive neon world.",
    difficulty: 3,
    tags: ["Rhythm", "Music", "Active", "Fitness"],
    playStyle: "Standing",
    actionType: "Rhythm Action",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620980/header.jpg",
    developer: "Beat Games",
    publisher: "Meta Quest Studios",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.2 GB",
    playerMode: "Single User / Multiplayer",
    features: [
      "Dual color light sabers physics",
      "360-degree immersive speaker tracks",
      "Custom beatmaps editor tool",
      "Active cardio fitness tracker dashboard"
    ]
  },
  {
    id: "motion-soccer-pro",
    title: "Motion Soccer Pro",
    category: "Sports & Fitness",
    suitability: "All Ages",
    shortDesc: "Show off your soccer skills as a striker or goalkeeper in VR.",
    longDesc: "Motion Soccer Pro brings the football pitch directly to you. Step up as the striker to score free kicks, or put on goalie gloves to block incoming balls in real-time. Fun, physical, and competitive soccer challenges.",
    difficulty: 2,
    tags: ["Sports", "Soccer", "Active", "Fun"],
    playStyle: "Standing/Room-Scale",
    actionType: "Soccer Simulator",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3137350/header.jpg",
    developer: "ProSports VR",
    publisher: "ProSports VR",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers (Goalie)",
    spaceRequired: "1.8 GB",
    playerMode: "Single User / Local Multiplayer",
    features: [
      "1:1 hand-tracking goalie mitts",
      "Penalty targeting grids",
      "Simulated crowd noise cheer loops",
      "Cardio calorie-burned readouts"
    ]
  },
  {
    id: "cooking-games",
    title: "The Cooking Game VR",
    category: "Sports & Fitness",
    suitability: "All Ages",
    shortDesc: "Chop, cook, and serve delicious dishes in a fast-paced virtual kitchen.",
    longDesc: "The Cooking Game VR puts you in charge of a busy, chaotic kitchen. Slice ingredients, fry burgers, assemble orders, and manage your time to keep customers happy. A physical and frantic cooking simulator that tests your hand-eye coordination.",
    difficulty: 2,
    tags: ["Simulation", "Cooking", "Time-Management", "Family"],
    playStyle: "Standing",
    actionType: "Cooking Simulator",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80",
    developer: "VR Kitchen",
    publisher: "VR Kitchen",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.1 GB",
    playerMode: "Single User",
    features: [
      "Functional stove, fryers & cutting boards",
      "Rush-hour countdown tickets",
      "Multi-recipe cooking sheets",
      "Clean-up & dishwasher simulator challenges"
    ]
  },

  // 7. Educational & Learning Experiences
  {
    id: "cosmic-vr",
    title: "Cosmic XR",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Educational Events",
    shortDesc: "Walk among the stars and explore our solar system up close.",
    longDesc: "Cosmic XR transforms your room into an interactive cosmos. Walk around planets, inspect orbits, witness supernovas, and see the scale of the universe in a visually stunning educational exploration of space.",
    difficulty: 1,
    tags: ["Space", "Astronomy", "Educational", "Interactive"],
    playStyle: "Sitting/Standing",
    actionType: "Science Simulation",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    developer: "Astronomy Labs",
    publisher: "Astronomy Labs",
    comfortRating: "Comfortable",
    controllers: "Touch/Hand Tracking",
    spaceRequired: "1.2 GB",
    playerMode: "Single User",
    features: [
      "Orbit path manipulation slider",
      "Planet size comparison maps",
      "Annotated stellar encyclopedias",
      "Supernova visual timeline animations"
    ]
  },
  {
    id: "human-anatomy-vr",
    title: "Human Anatomy VR",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Educational Events",
    shortDesc: "Inspect a highly detailed 3D map of the human body.",
    longDesc: "Human Anatomy VR provides a groundbreaking way to learn biology. Dissect muscle layers, trace blood flow, view skeletal structures, and zoom into specific organs in full 3D interactive space. Ideal for students and biology events.",
    difficulty: 1,
    tags: ["Biology", "Anatomy", "Educational", "Interactive"],
    playStyle: "Sitting/Standing",
    actionType: "Science Exploration",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?auto=format&fit=crop&w=600&q=80",
    developer: "Virtual Medicine",
    publisher: "Virtual Medicine",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.5 GB",
    playerMode: "Single User",
    features: [
      "Muscle & bone layer dissection",
      "Animated blood flow simulations",
      "High-power zoom organ examinations",
      "Integrated biology quiz sets"
    ]
  },
  {
    id: "natgeo-explore",
    title: "National Geographic Explore VR",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Educational Events",
    shortDesc: "Travel to Antarctica and Machu Picchu on a virtual expedition.",
    longDesc: "National Geographic Explore VR lets you travel to the ends of the Earth. Navigate icebergs in a kayak, climb a giant ice wall, survive a blizzard, and explore the ancient ruins of Machu Picchu while taking photos for National Geographic.",
    difficulty: 2,
    tags: ["Adventure", "Geography", "Educational", "Interactive"],
    playStyle: "Standing/Room-Scale",
    actionType: "Virtual Travel",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    developer: "Force Field VR",
    publisher: "National Geographic",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "3.0 GB",
    playerMode: "Single User",
    features: [
      "Realistic kayak paddling mechanics",
      "Ice climbing rope and pick physics",
      "Expedition field camera lens system",
      "Immersive weather blizzard cycles"
    ]
  },
  {
    id: "overview-360",
    title: "Sky Overview 360",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Educational Events",
    shortDesc: "Fly around the globe and view earth's structures in 360-degree glory.",
    longDesc: "Sky Overview 360 gives you an astronaut's perspective of planet Earth. Fly around orbits, see cities lit up at night, watch weather cycles move across the atmosphere, and learn about satellite telemetry in a relaxed orbital simulation.",
    difficulty: 1,
    tags: ["Space", "Earth", "Relaxing", "Cinematic"],
    playStyle: "Sitting",
    actionType: "Cinematic Experience",
    image: "https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?auto=format&fit=crop&w=600&q=80",
    developer: "NASA Space Apps",
    publisher: "NASA Space Apps",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.5 GB",
    playerMode: "Single User",
    features: [
      "HD satellite texture overlays",
      "Dynamic weather storm trackers",
      "Orbit telemetry readouts",
      "Interactive globe spinning control"
    ]
  },
  {
    id: "ambulate-to-wheelchair",
    title: "Ambulate to Wheelchair",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Healthcare Events",
    shortDesc: "Train in clinical patient mobilization from a bed to a wheelchair.",
    longDesc: "Ambulate to Wheelchair is an interactive medical nursing training simulator. Practice body mechanics, safety locking, pivot steps, and communication cues while assisting a virtual patient from their bedside into a wheelchair.",
    difficulty: 2,
    tags: ["Medical", "Healthcare", "Nursing", "Simulation"],
    playStyle: "Standing",
    actionType: "Nursing Simulation",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=600&q=80",
    developer: "HealthSim VR",
    publisher: "HealthSim VR",
    comfortRating: "Comfortable",
    controllers: "Hand Tracking / Touch",
    spaceRequired: "1.4 GB",
    playerMode: "Single User",
    features: [
      "Nursing ergonomics feedback detector",
      "Real-time weight shifting gauges",
      "Dialogue communication queues",
      "Safety brake validation check"
    ]
  },
  {
    id: "hallo-einstein",
    title: "Hallo Einstein",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Educational Events",
    shortDesc: "Enter Albert Einstein's study and explore theoretical physics.",
    longDesc: "Hallo Einstein places you inside the historic patent office. Solve physics puzzles, slide blocks to test special relativity, and converse with an interactive animated Albert Einstein in a charming historical simulator.",
    difficulty: 1,
    tags: ["Physics", "History", "Science", "Interactives"],
    playStyle: "Sitting/Standing",
    actionType: "Science Laboratory",
    image: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=600&q=80",
    developer: "Science Museum VR",
    publisher: "Science Museum VR",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.6 GB",
    playerMode: "Single User",
    features: [
      "Relativity chalkboard drawings",
      "Conversation engines with Einstein",
      "Patent office historical tours",
      "Physics velocity block experiments"
    ]
  },
  {
    id: "10k-science",
    title: "10K Science",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Educational Events",
    shortDesc: "Perform chemical experiments safely inside a virtual science lab.",
    longDesc: "10K Science is a comprehensive virtual chemistry and biology laboratory. Mix elements, run centrifuges, observe micro-organisms through virtual microscopes, and complete safe, curriculum-aligned experiments.",
    difficulty: 2,
    tags: ["Chemistry", "Biology", "Science", "School"],
    playStyle: "Standing",
    actionType: "Science Laboratory",
    image: "https://images.unsplash.com/photo-1532187640605-a33d9107988c?auto=format&fit=crop&w=600&q=80",
    developer: "School Labs",
    publisher: "School Labs",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "2.0 GB",
    playerMode: "Single User",
    features: [
      "Interactive periodic element mixing",
      "Functional slides & microscopes",
      "Chemical fire safety drills",
      "Curriculum-aligned chemical guides"
    ]
  },
  {
    id: "ambulate-transfer-belt",
    title: "Ambulate Transfer Belt",
    category: "Educational & Learning Experiences",
    suitability: "Schools & Healthcare Events",
    shortDesc: "Learn nursing safety procedures using physical gait transfer belts.",
    longDesc: "Ambulate Transfer Belt teaches nursing and physical therapy safety guidelines. Practice adjusting, tightening, and holding gait belts while lifting, supporting, and walking patients through rehabilitation paths.",
    difficulty: 2,
    tags: ["Medical", "Healthcare", "Nursing", "Training"],
    playStyle: "Standing",
    actionType: "Nursing Simulation",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80",
    developer: "HealthSim VR",
    publisher: "HealthSim VR",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "1.3 GB",
    playerMode: "Single User",
    features: [
      "Physiotherapy gait belt adjustments",
      "Real-time spine strain detectors",
      "Interactive patient safety triggers",
      "Assisted walking training corridors"
    ]
  },
  {
    id: "world-lens-vr",
    title: "World Lens VR",
    category: "Educational & Learning Experiences",
    suitability: "All Ages",
    shortDesc: "Explore global landmarks and heritage sites in 360-degree tours.",
    longDesc: "World Lens VR is a travel documentarian simulator. Travel to the Great Wall of China, Eiffel Tower, Colosseum, and more, reading built-in histories, taking 3D photos, and discovering cultural milestones.",
    difficulty: 1,
    tags: ["Geography", "History", "Travel", "Nature"],
    playStyle: "Sitting/Standing",
    actionType: "Virtual Traveling",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80",
    developer: "Travel Media",
    publisher: "Travel Media",
    comfortRating: "Comfortable",
    controllers: "Touch Controllers",
    spaceRequired: "2.2 GB",
    playerMode: "Single User",
    features: [
      "360 historical sight overlays",
      "Voiceover translation guides",
      "Historical zoom magnifying lenses",
      "Interactive map search selectors"
    ]
  },
  {
    id: "wander",
    title: "Wander",
    category: "Educational & Learning Experiences",
    suitability: "All Ages",
    shortDesc: "Teleport to any street or landmark on Earth using Google Street View.",
    longDesc: "Wander lets you explore the entire globe from a street-level perspective. Walk through your childhood neighborhood, visit polar reserves, or scale historic squares with voice search and cooperative multiplayer tours.",
    difficulty: 1,
    tags: ["Geography", "Maps", "Travel", "Relaxing"],
    playStyle: "Sitting/Standing",
    actionType: "Virtual Exploration",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=600&q=80",
    developer: "Parkline Studio",
    publisher: "Parkline Studio",
    comfortRating: "Comfortable",
    controllers: "Touch/Hand Tracking",
    spaceRequired: "1.4 GB",
    playerMode: "Single User / Co-op",
    features: [
      "Google Street View mapping overlays",
      "Time-travel historical photo sliders",
      "Co-op multiplayer voice tours",
      "Integrated Wikipedia reference blocks"
    ]
  }
];
